fragment PeliculaParts on Pelicula {
  __typename
  title
  poster
  synopsis
  credits
  showDate
  showTime
  showEndTime
  featured
  duration
  country
  location
}

fragment EventoParts on Evento {
  __typename
  title
  poster
  description
  date
  eventTime
  eventEndTime
  featured
  location
}
