fragment PeliculaParts on Pelicula {
  __typename
  title
  poster
  cancelled
  youtubeTrailer
  synopsis
  credits
  showDate
  showTime
  showEndTime
  featured
  duration
  country
  location {
    ... on Ubicacion {
      __typename
      title
      address
      mapCoordinates
      instagramReel
      image
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  isPartOfEvent {
    ... on Evento {
      __typename
      title
      poster
      cancelled
      youtubeTrailer
      description
      date
      eventTime
      eventEndTime
      featured
      location {
        ... on Ubicacion {
          __typename
          title
          address
          mapCoordinates
          instagramReel
          image
        }
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
      }
      shortFilms {
        __typename
        title
        director
        duration
        synopsis
      }
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
}

fragment EventoParts on Evento {
  __typename
  title
  poster
  cancelled
  youtubeTrailer
  description
  date
  eventTime
  eventEndTime
  featured
  location {
    ... on Ubicacion {
      __typename
      title
      address
      mapCoordinates
      instagramReel
      image
    }
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
  }
  shortFilms {
    __typename
    title
    director
    duration
    synopsis
  }
}

fragment UbicacionParts on Ubicacion {
  __typename
  title
  address
  mapCoordinates
  instagramReel
  image
}

fragment QuienesSomosParts on QuienesSomos {
  __typename
  title
  image
  content
}
