//@ts-nocheck
  // DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
  export function gql(strings: TemplateStringsArray, ...args: string[]): string {
    let str = ''
    strings.forEach((string, i) => {
      str += string + (args[i] || '')
    })
    return str
  }
  export type Maybe<T> = T | null;
export type InputMaybe<T> = Maybe<T>;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
export type MakeEmpty<T extends { [key: string]: unknown }, K extends keyof T> = { [_ in K]?: never };
export type Incremental<T> = T | { [P in keyof T]?: P extends ' $fragmentName' | '__typename' ? T[P] : never };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: { input: string; output: string; }
  String: { input: string; output: string; }
  Boolean: { input: boolean; output: boolean; }
  Int: { input: number; output: number; }
  Float: { input: number; output: number; }
  /** References another document, used as a foreign key */
  Reference: { input: any; output: any; }
  JSON: { input: any; output: any; }
};

export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String']['output'];
  title?: Maybe<Scalars['String']['output']>;
  basename: Scalars['String']['output'];
  hasReferences?: Maybe<Scalars['Boolean']['output']>;
  breadcrumbs: Array<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  relativePath: Scalars['String']['output'];
  extension: Scalars['String']['output'];
  template: Scalars['String']['output'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: InputMaybe<Scalars['Boolean']['input']>;
};

export type Folder = {
  __typename?: 'Folder';
  name: Scalars['String']['output'];
  path: Scalars['String']['output'];
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean']['output'];
  hasNextPage: Scalars['Boolean']['output'];
  startCursor: Scalars['String']['output'];
  endCursor: Scalars['String']['output'];
};

export type Node = {
  id: Scalars['ID']['output'];
};

export type Document = {
  id: Scalars['ID']['output'];
  _sys?: Maybe<SystemInfo>;
  _values: Scalars['JSON']['output'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Float']['output'];
  pageInfo: PageInfo;
};

export type Query = {
  __typename?: 'Query';
  getOptimizedQuery?: Maybe<Scalars['String']['output']>;
  collection: Collection;
  collections: Array<Collection>;
  node: Node;
  document: DocumentNode;
  pelicula: Pelicula;
  peliculaConnection: PeliculaConnection;
  evento: Evento;
  eventoConnection: EventoConnection;
};


export type QueryGetOptimizedQueryArgs = {
  queryString: Scalars['String']['input'];
};


export type QueryCollectionArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
};


export type QueryNodeArgs = {
  id?: InputMaybe<Scalars['String']['input']>;
};


export type QueryDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPeliculaArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryPeliculaConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeliculaFilter>;
};


export type QueryEventoArgs = {
  relativePath?: InputMaybe<Scalars['String']['input']>;
};


export type QueryEventoConnectionArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventoFilter>;
};

export type DocumentFilter = {
  pelicula?: InputMaybe<PeliculaFilter>;
  evento?: InputMaybe<EventoFilter>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String']['output'];
  slug: Scalars['String']['output'];
  label?: Maybe<Scalars['String']['output']>;
  path: Scalars['String']['output'];
  format?: Maybe<Scalars['String']['output']>;
  matches?: Maybe<Scalars['String']['output']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']['output']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<DocumentFilter>;
  folder?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentNode = Pelicula | Evento | Folder;

export type Pelicula = Node & Document & {
  __typename?: 'Pelicula';
  title: Scalars['String']['output'];
  poster: Scalars['String']['output'];
  synopsis: Scalars['String']['output'];
  credits?: Maybe<Scalars['String']['output']>;
  showDate: Scalars['String']['output'];
  status: Scalars['String']['output'];
  duration?: Maybe<Scalars['Float']['output']>;
  country?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type StringFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type ImageFilter = {
  startsWith?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type DatetimeFilter = {
  after?: InputMaybe<Scalars['String']['input']>;
  before?: InputMaybe<Scalars['String']['input']>;
  eq?: InputMaybe<Scalars['String']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['String']['input']>>>;
};

export type NumberFilter = {
  lt?: InputMaybe<Scalars['Float']['input']>;
  lte?: InputMaybe<Scalars['Float']['input']>;
  gte?: InputMaybe<Scalars['Float']['input']>;
  gt?: InputMaybe<Scalars['Float']['input']>;
  eq?: InputMaybe<Scalars['Float']['input']>;
  exists?: InputMaybe<Scalars['Boolean']['input']>;
  in?: InputMaybe<Array<InputMaybe<Scalars['Float']['input']>>>;
};

export type PeliculaFilter = {
  title?: InputMaybe<StringFilter>;
  poster?: InputMaybe<ImageFilter>;
  synopsis?: InputMaybe<StringFilter>;
  credits?: InputMaybe<StringFilter>;
  showDate?: InputMaybe<DatetimeFilter>;
  status?: InputMaybe<StringFilter>;
  duration?: InputMaybe<NumberFilter>;
  country?: InputMaybe<StringFilter>;
};

export type PeliculaConnectionEdges = {
  __typename?: 'PeliculaConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Pelicula>;
};

export type PeliculaConnection = Connection & {
  __typename?: 'PeliculaConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<PeliculaConnectionEdges>>>;
};

export type Evento = Node & Document & {
  __typename?: 'Evento';
  title: Scalars['String']['output'];
  poster: Scalars['String']['output'];
  description: Scalars['String']['output'];
  date: Scalars['String']['output'];
  location?: Maybe<Scalars['String']['output']>;
  id: Scalars['ID']['output'];
  _sys: SystemInfo;
  _values: Scalars['JSON']['output'];
};

export type EventoFilter = {
  title?: InputMaybe<StringFilter>;
  poster?: InputMaybe<ImageFilter>;
  description?: InputMaybe<StringFilter>;
  date?: InputMaybe<DatetimeFilter>;
  location?: InputMaybe<StringFilter>;
};

export type EventoConnectionEdges = {
  __typename?: 'EventoConnectionEdges';
  cursor: Scalars['String']['output'];
  node?: Maybe<Evento>;
};

export type EventoConnection = Connection & {
  __typename?: 'EventoConnection';
  pageInfo: PageInfo;
  totalCount: Scalars['Float']['output'];
  edges?: Maybe<Array<Maybe<EventoConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  deleteDocument: DocumentNode;
  createDocument: DocumentNode;
  createFolder: DocumentNode;
  updatePelicula: Pelicula;
  createPelicula: Pelicula;
  updateEvento: Evento;
  createEvento: Evento;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String']['input'];
  relativePath: Scalars['String']['input'];
  template?: InputMaybe<Scalars['String']['input']>;
};


export type MutationUpdateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentUpdateMutation;
};


export type MutationDeleteDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationCreateDocumentArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
  params: DocumentMutation;
};


export type MutationCreateFolderArgs = {
  collection?: InputMaybe<Scalars['String']['input']>;
  relativePath: Scalars['String']['input'];
};


export type MutationUpdatePeliculaArgs = {
  relativePath: Scalars['String']['input'];
  params: PeliculaMutation;
};


export type MutationCreatePeliculaArgs = {
  relativePath: Scalars['String']['input'];
  params: PeliculaMutation;
};


export type MutationUpdateEventoArgs = {
  relativePath: Scalars['String']['input'];
  params: EventoMutation;
};


export type MutationCreateEventoArgs = {
  relativePath: Scalars['String']['input'];
  params: EventoMutation;
};

export type DocumentUpdateMutation = {
  pelicula?: InputMaybe<PeliculaMutation>;
  evento?: InputMaybe<EventoMutation>;
  relativePath?: InputMaybe<Scalars['String']['input']>;
};

export type DocumentMutation = {
  pelicula?: InputMaybe<PeliculaMutation>;
  evento?: InputMaybe<EventoMutation>;
};

export type PeliculaMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  poster?: InputMaybe<Scalars['String']['input']>;
  synopsis?: InputMaybe<Scalars['String']['input']>;
  credits?: InputMaybe<Scalars['String']['input']>;
  showDate?: InputMaybe<Scalars['String']['input']>;
  status?: InputMaybe<Scalars['String']['input']>;
  duration?: InputMaybe<Scalars['Float']['input']>;
  country?: InputMaybe<Scalars['String']['input']>;
};

export type EventoMutation = {
  title?: InputMaybe<Scalars['String']['input']>;
  poster?: InputMaybe<Scalars['String']['input']>;
  description?: InputMaybe<Scalars['String']['input']>;
  date?: InputMaybe<Scalars['String']['input']>;
  location?: InputMaybe<Scalars['String']['input']>;
};

export type PeliculaPartsFragment = { __typename: 'Pelicula', title: string, poster: string, synopsis: string, credits?: string | null, showDate: string, status: string, duration?: number | null, country?: string | null };

export type EventoPartsFragment = { __typename: 'Evento', title: string, poster: string, description: string, date: string, location?: string | null };

export type PeliculaQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type PeliculaQuery = { __typename?: 'Query', pelicula: { __typename: 'Pelicula', id: string, title: string, poster: string, synopsis: string, credits?: string | null, showDate: string, status: string, duration?: number | null, country?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type PeliculaConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<PeliculaFilter>;
}>;


export type PeliculaConnectionQuery = { __typename?: 'Query', peliculaConnection: { __typename?: 'PeliculaConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'PeliculaConnectionEdges', cursor: string, node?: { __typename: 'Pelicula', id: string, title: string, poster: string, synopsis: string, credits?: string | null, showDate: string, status: string, duration?: number | null, country?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export type EventoQueryVariables = Exact<{
  relativePath: Scalars['String']['input'];
}>;


export type EventoQuery = { __typename?: 'Query', evento: { __typename: 'Evento', id: string, title: string, poster: string, description: string, date: string, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } };

export type EventoConnectionQueryVariables = Exact<{
  before?: InputMaybe<Scalars['String']['input']>;
  after?: InputMaybe<Scalars['String']['input']>;
  first?: InputMaybe<Scalars['Float']['input']>;
  last?: InputMaybe<Scalars['Float']['input']>;
  sort?: InputMaybe<Scalars['String']['input']>;
  filter?: InputMaybe<EventoFilter>;
}>;


export type EventoConnectionQuery = { __typename?: 'Query', eventoConnection: { __typename?: 'EventoConnection', totalCount: number, pageInfo: { __typename?: 'PageInfo', hasPreviousPage: boolean, hasNextPage: boolean, startCursor: string, endCursor: string }, edges?: Array<{ __typename?: 'EventoConnectionEdges', cursor: string, node?: { __typename: 'Evento', id: string, title: string, poster: string, description: string, date: string, location?: string | null, _sys: { __typename?: 'SystemInfo', filename: string, basename: string, hasReferences?: boolean | null, breadcrumbs: Array<string>, path: string, relativePath: string, extension: string } } | null } | null> | null } };

export const PeliculaPartsFragmentDoc = gql`
    fragment PeliculaParts on Pelicula {
  __typename
  title
  poster
  synopsis
  credits
  showDate
  status
  duration
  country
}
    `;
export const EventoPartsFragmentDoc = gql`
    fragment EventoParts on Evento {
  __typename
  title
  poster
  description
  date
  location
}
    `;
export const PeliculaDocument = gql`
    query pelicula($relativePath: String!) {
  pelicula(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...PeliculaParts
  }
}
    ${PeliculaPartsFragmentDoc}`;
export const PeliculaConnectionDocument = gql`
    query peliculaConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: PeliculaFilter) {
  peliculaConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...PeliculaParts
      }
    }
  }
}
    ${PeliculaPartsFragmentDoc}`;
export const EventoDocument = gql`
    query evento($relativePath: String!) {
  evento(relativePath: $relativePath) {
    ... on Document {
      _sys {
        filename
        basename
        hasReferences
        breadcrumbs
        path
        relativePath
        extension
      }
      id
    }
    ...EventoParts
  }
}
    ${EventoPartsFragmentDoc}`;
export const EventoConnectionDocument = gql`
    query eventoConnection($before: String, $after: String, $first: Float, $last: Float, $sort: String, $filter: EventoFilter) {
  eventoConnection(
    before: $before
    after: $after
    first: $first
    last: $last
    sort: $sort
    filter: $filter
  ) {
    pageInfo {
      hasPreviousPage
      hasNextPage
      startCursor
      endCursor
    }
    totalCount
    edges {
      cursor
      node {
        ... on Document {
          _sys {
            filename
            basename
            hasReferences
            breadcrumbs
            path
            relativePath
            extension
          }
          id
        }
        ...EventoParts
      }
    }
  }
}
    ${EventoPartsFragmentDoc}`;
export type Requester<C= {}> = <R, V>(doc: DocumentNode, vars?: V, options?: C) => Promise<R>
  export function getSdk<C>(requester: Requester<C>) {
    return {
      pelicula(variables: PeliculaQueryVariables, options?: C): Promise<{data: PeliculaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeliculaQueryVariables, query: string}> {
        return requester<{data: PeliculaQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeliculaQueryVariables, query: string}, PeliculaQueryVariables>(PeliculaDocument, variables, options);
      },
    peliculaConnection(variables?: PeliculaConnectionQueryVariables, options?: C): Promise<{data: PeliculaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeliculaConnectionQueryVariables, query: string}> {
        return requester<{data: PeliculaConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: PeliculaConnectionQueryVariables, query: string}, PeliculaConnectionQueryVariables>(PeliculaConnectionDocument, variables, options);
      },
    evento(variables: EventoQueryVariables, options?: C): Promise<{data: EventoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventoQueryVariables, query: string}> {
        return requester<{data: EventoQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventoQueryVariables, query: string}, EventoQueryVariables>(EventoDocument, variables, options);
      },
    eventoConnection(variables?: EventoConnectionQueryVariables, options?: C): Promise<{data: EventoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventoConnectionQueryVariables, query: string}> {
        return requester<{data: EventoConnectionQuery, errors?: { message: string, locations: { line: number, column: number }[], path: string[] }[], variables: EventoConnectionQueryVariables, query: string}, EventoConnectionQueryVariables>(EventoConnectionDocument, variables, options);
      }
    };
  }
  export type Sdk = ReturnType<typeof getSdk>;

// TinaSDK generated code
import { createClient, TinaClient } from "tinacms/dist/client";

const generateRequester = (
  client: TinaClient,
) => {
  const requester: (
    doc: any,
    vars?: any,
    options?: {
      branch?: string,
      /**
       * Aside from `method` and `body`, all fetch options are passed
       * through to underlying fetch request
       */
      fetchOptions?: Omit<Parameters<typeof fetch>[1], 'body' | 'method'>,
    },
    client
  ) => Promise<any> = async (doc, vars, options) => {
    let url = client.apiUrl
    if (options?.branch) {
      const index = client.apiUrl.lastIndexOf('/')
      url = client.apiUrl.substring(0, index + 1) + options.branch
    }
    const data = await client.request({
      query: doc,
      variables: vars,
      url,
    }, options)

    return { data: data?.data, errors: data?.errors, query: doc, variables: vars || {} }
  }

  return requester
}

/**
 * @experimental this class can be used but may change in the future
 **/
export const ExperimentalGetTinaClient = () =>
  getSdk(
    generateRequester(
      createClient({
        url: "http://localhost:4001/graphql",
        queries,
      })
    )
  )

export const queries = (
  client: TinaClient,
) => {
  const requester = generateRequester(client)
  return getSdk(requester)
}

  